version: 2
registries:
  redhatregistry:
    type: docker-registry
    url: registry.access.redhat.com
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "GitHub Actions"
      include: "scope"
  # Maintain dependencies for pom.xml
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "Maven pom.xml"
      include: "scope"
  # Maintain container images in Dockerfiles based on Red Hat registry
  - package-ecosystem: "docker"
    directory: "/"
    registries: "*"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "Dockerfile"
      include: "scope"
