#
# Copyright © 2021 the Konveyor Contributors (https://konveyor.io/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-analysis
  labels:
    app.kubernetes.io/name: shared-analysis
    app.kubernetes.io/component: storage
    app.kubernetes.io/instance: shared-analysis
    app.kubernetes.io/part-of: windup-api
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: central-graph
  labels:
    app.kubernetes.io/name: central-graph
    app.kubernetes.io/component: storage
    app.kubernetes.io/instance: central-graph
    app.kubernetes.io/part-of: windup-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # 10 Gi due to https://docs.oracle.com/cd/E17277_02/html/java/com/sleepycat/je/EnvironmentConfig.html#FREE_DISK
      storage: 10Gi
  volumeMode: Filesystem
---
apiVersion: v1
kind: Service
metadata:
  name: artemis
  labels:
    app.kubernetes.io/name: artemis
    app.kubernetes.io/component: jms-broker
    app.kubernetes.io/instance: artemis
    app.kubernetes.io/part-of: windup-api
spec:
  ports:
    - name: tcp
      protocol: TCP
      port: 61616
      targetPort: 61616
  selector:
    app.kubernetes.io/name: artemis
---
apiVersion: v1
kind: Service
metadata:
  name: artemis-console
  labels:
    app.kubernetes.io/name: artemis-console
    app.kubernetes.io/component: jms-broker
    app.kubernetes.io/instance: artemis-console
    app.kubernetes.io/part-of: windup-api
spec:
  ports:
    - name: http
      port: 8161
      targetPort: 8161
  selector:
    app.kubernetes.io/name: artemis
  type: LoadBalancer
---
kind: Service
apiVersion: v1
metadata:
  name: api
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/component: windup-api
    app.kubernetes.io/instance: api
    app.kubernetes.io/part-of: windup-api
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: windup-api
  type: LoadBalancer
  sessionAffinity: None
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: artemis
  labels:
    app.kubernetes.io/name: artemis
    app.kubernetes.io/component: jms-broker
    app.kubernetes.io/instance: artemis
    app.kubernetes.io/part-of: windup-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: artemis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: artemis
    spec:
      containers:
        - name: artemis
          image: quay.io/artemiscloud/activemq-artemis-broker:1.0.19
          ports:
            - containerPort: 61616
              protocol: TCP
            - containerPort: 8161
              protocol: TCP
          env:
            - name: AMQ_USER
              value: quarkus
            - name: AMQ_PASSWORD
              value: quarkus
          resources: {}
          livenessProbe:
            httpGet:
              path: /
              port: 8161
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8161
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: windup-executor
  labels:
    app.kubernetes.io/name: windup-executor
    app.kubernetes.io/component: windup
    app.kubernetes.io/instance: windup-executor
    app.kubernetes.io/part-of: windup-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: windup-executor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: windup-executor
    spec:
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-analysis
      containers:
        - name: windup-executor
#          image: localhost/mrizzi/windup-web-openshift-messaging-executor:5.2.1-SNAPSHOT
          image: quay.io/mrizzi/windup-web-openshift-messaging-executor:20220114182336CET
#          resources:
#            requests:
#              cpu: 2
#              memory: 4Gi
#            limits:
#              cpu: 2
#              memory: 4Gi
          env:
            - name: MESSAGING_USER
              value: "quarkus"
            - name: MESSAGING_PASSWORD
              value: "quarkus"
            - name: MESSAGING_HOST_VAR
              value: "jms-url"
            - name: JMS_URL
              value: "ARTEMIS"
          volumeMounts:
            - name: shared-volume
              mountPath: /opt/windup/shared
          lifecycle:
            preStop:
              exec:
                command: 
                  - /opt/mta-cli/bin/stop.sh
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - "-c"
                - /opt/mta-cli/bin/livenessProbe.sh
            initialDelaySeconds: 60
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - "-c"
                - /opt/mta-cli/bin/livenessProbe.sh
            initialDelaySeconds: 120
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 6
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: windup-api
  labels:
    app.kubernetes.io/name: windup-api
    app.kubernetes.io/component: API
    app.kubernetes.io/instance: windup-api
    app.kubernetes.io/part-of: windup-api
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: windup-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: windup-api
    spec:
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-analysis
        - name: central-graph
          persistentVolumeClaim:
            claimName: central-graph
      initContainers:
        - name: init-config
          image: busybox:latest
          command: ['sh', '-c', "until wget -T 1 http://${ARTEMIS_CONSOLE_SERVICE_HOST}:${ARTEMIS_CONSOLE_SERVICE_PORT}/; do echo waiting for artemis; sleep 2; done"]
      containers:
        - name: windup-api
          image: localhost/{user}/windup-api:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: IO_TACKLE_WINDUP_REST_SHARED_FOLDER_PATH
              value: "/opt/windup/shared"
            - name: QUARKUS_ARTEMIS_URL
              value: "tcp://artemis:61616"
            - name: QUARKUS_LOG_LEVEL
#              value: "DEBUG"
              value: "INFO"
            - name: QUARKUS_HTTP_LIMITS_MAX_BODY_SIZE
              value: "100M"
          volumeMounts:
            - name: shared-volume
              mountPath: /opt/windup/shared/
            - name: central-graph
              mountPath: /opt/windup/central-graph/
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            failureThreshold: 3
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          imagePullPolicy: IfNotPresent
